// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Context;

#nullable disable

namespace FilmApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250722071808_UpdateMovieSeedData")]
    partial class UpdateMovieSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmApi.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FilmApi.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ea451e8-e763-446c-adc5-0a84f58f1d64"),
                            Description = "Tv domates explicabo amet değerli tempora çorba dolore ışık. Mi çakıl odio koyun vitae sıradanlıktan beatae. Et ab için dolore voluptatem duyulmamış.",
                            Director = "Erinç Menemencioğlu",
                            Genre = 4,
                            ReleaseDate = new DateTime(2021, 1, 31, 7, 16, 18, 824, DateTimeKind.Local).AddTicks(4893),
                            Title = "Tempora explicabo magni."
                        },
                        new
                        {
                            Id = new Guid("fc773e40-681a-41af-b592-224e31016116"),
                            Description = "Tv kapının balıkhaneye. Sarmal sıfat ve sıla quia ratione kapının consequatur magnam kutusu. Nihil mutlu filmini ducimus ea adresini gidecekmiş ona ipsam.",
                            Director = "Beçkem Akgül",
                            Genre = 7,
                            ReleaseDate = new DateTime(2023, 3, 28, 6, 51, 6, 751, DateTimeKind.Local).AddTicks(2280),
                            Title = "Odio çarpan eos."
                        },
                        new
                        {
                            Id = new Guid("1d3a4cc6-2c4c-4bc5-953c-a3227308a111"),
                            Description = "Dağılımı laboriosam de. Ötekinden neque consectetur laboriosam sıfat minima öyle. Nostrum nemo koştum ut neque.",
                            Director = "Çiğdem Erberk",
                            Genre = 8,
                            ReleaseDate = new DateTime(2017, 7, 2, 1, 6, 20, 403, DateTimeKind.Local).AddTicks(7459),
                            Title = "Biber molestiae voluptatem."
                        },
                        new
                        {
                            Id = new Guid("c4f85cd2-7400-4e0f-9fc4-3560d1162bdb"),
                            Description = "Non layıkıyla duyulmamış enim sıradanlıktan rem ad beatae vel dışarı. Lambadaki adipisci consectetur duyulmamış. Gidecekmiş quaerat biber consequatur patlıcan voluptatem quae adipisci aut. İpsam nostrum ea un layıkıyla doğru iure doğru.",
                            Director = "Altıntay Körmükçü",
                            Genre = 8,
                            ReleaseDate = new DateTime(2024, 3, 18, 6, 0, 37, 812, DateTimeKind.Local).AddTicks(3472),
                            Title = "Biber quia masanın."
                        },
                        new
                        {
                            Id = new Guid("47fc5eb6-c7e0-4aac-8e9b-f4db504a49e7"),
                            Description = "Masanın aut koyun aliquid karşıdakine quam. Nisi ducimus non dolorem magni. Suscipit sit sıfat eius alias okuma suscipit. Eve gidecekmiş alias consectetur eius. Doğru olduğu kapının.",
                            Director = "Aydın Akgül",
                            Genre = 10,
                            ReleaseDate = new DateTime(2018, 10, 28, 21, 24, 25, 30, DateTimeKind.Local).AddTicks(1811),
                            Title = "İpsa ullam dolorem."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
